
		var gioi_thieu1='<p class="title">Về Đại Ngân 1</p><p>Nội thất Xuân hòa được thành lập từ năm 1980. Sau hơn 30 năm không ngừng phát triển, đến nay Xuân Hòa tự hào là một trong những doanh nghiệp hàng đầu về tư vấn, thiết kế, sản xuất trang thiết bị nội thất.</p><p class="center-red">"Mãi gắn bó, Mãi bền lâu"</p><figure><img src="img/blank-picture.jpg"><figcaption>Nhận diện thương hiệu mới nội thất xuân hòa</figcaption></figure><b>Trụ sở chính/Nhà máy</b><p>Địa chỉ: Xuân Hòa – Phúc Yên – Vĩnh Phúc</p><p>Phân phối tại Hà Nội</p><b>NỘI THẤT XUÂN HÒA</b><p>Địa chỉ: Tầng 1 Tòa nhà CT3B số 10 Đại Lộ Thăng Long, Mễ Trì, Nam Từ Liêm, Hà Nội</p><p>Điện thoại: 04 33676688 - Hotline: 0982299076</p><p class="center-black">Xin mời các bạn xem thêm thông tin về nhà máy Xuân hòa Qua Video sau</p><iframe width="100%" height="300" src="https://www.youtube.com/embed/I61l7eltucM" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>';
		var gioi_thieu2='<p class="title">Về Đại Ngân 2</p><p>Nội thất Xuân hòa được thành lập từ năm 1980. Sau hơn 30 năm không ngừng phát triển, đến nay Xuân Hòa tự hào là một trong những doanh nghiệp hàng đầu về tư vấn, thiết kế, sản xuất trang thiết bị nội thất.</p><p class="center-red">"Mãi gắn bó, Mãi bền lâu"</p><figure><img src="img/blank-picture.jpg"><figcaption>Nhận diện thương hiệu mới nội thất xuân hòa</figcaption></figure><b>Trụ sở chính/Nhà máy</b><p>Địa chỉ: Xuân Hòa – Phúc Yên – Vĩnh Phúc</p><p>Phân phối tại Hà Nội</p><b>NỘI THẤT XUÂN HÒA</b><p>Địa chỉ: Tầng 1 Tòa nhà CT3B số 10 Đại Lộ Thăng Long, Mễ Trì, Nam Từ Liêm, Hà Nội</p><p>Điện thoại: 04 33676688 - Hotline: 0982299076</p><p class="center-black">Xin mời các bạn xem thêm thông tin về nhà máy Xuân hòa Qua Video sau</p><iframe width="100%" height="300" src="https://www.youtube.com/embed/I61l7eltucM" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>';
		var gioi_thieu3='<p class="title">Về Đại Ngân 3</p><p>Nội thất Xuân hòa được thành lập từ năm 1980. Sau hơn 30 năm không ngừng phát triển, đến nay Xuân Hòa tự hào là một trong những doanh nghiệp hàng đầu về tư vấn, thiết kế, sản xuất trang thiết bị nội thất.</p><p class="center-red">"Mãi gắn bó, Mãi bền lâu"</p><figure><img src="img/blank-picture.jpg"><figcaption>Nhận diện thương hiệu mới nội thất xuân hòa</figcaption></figure><b>Trụ sở chính/Nhà máy</b><p>Địa chỉ: Xuân Hòa – Phúc Yên – Vĩnh Phúc</p><p>Phân phối tại Hà Nội</p><b>NỘI THẤT XUÂN HÒA</b><p>Địa chỉ: Tầng 1 Tòa nhà CT3B số 10 Đại Lộ Thăng Long, Mễ Trì, Nam Từ Liêm, Hà Nội</p><p>Điện thoại: 04 33676688 - Hotline: 0982299076</p><p class="center-black">Xin mời các bạn xem thêm thông tin về nhà máy Xuân hòa Qua Video sau</p><iframe width="100%" height="300" src="https://www.youtube.com/embed/I61l7eltucM" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>';
		var gioi_thieu4='<p class="title">Về Đại Ngân 4</p><p>Nội thất Xuân hòa được thành lập từ năm 1980. Sau hơn 30 năm không ngừng phát triển, đến nay Xuân Hòa tự hào là một trong những doanh nghiệp hàng đầu về tư vấn, thiết kế, sản xuất trang thiết bị nội thất.</p><p class="center-red">"Mãi gắn bó, Mãi bền lâu"</p><figure><img src="img/blank-picture.jpg"><figcaption>Nhận diện thương hiệu mới nội thất xuân hòa</figcaption></figure><b>Trụ sở chính/Nhà máy</b><p>Địa chỉ: Xuân Hòa – Phúc Yên – Vĩnh Phúc</p><p>Phân phối tại Hà Nội</p><b>NỘI THẤT XUÂN HÒA</b><p>Địa chỉ: Tầng 1 Tòa nhà CT3B số 10 Đại Lộ Thăng Long, Mễ Trì, Nam Từ Liêm, Hà Nội</p><p>Điện thoại: 04 33676688 - Hotline: 0982299076</p><p class="center-black">Xin mời các bạn xem thêm thông tin về nhà máy Xuân hòa Qua Video sau</p><iframe width="100%" height="300" src="https://www.youtube.com/embed/I61l7eltucM" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>';
		var gioi_thieu5='<p class="title">Về Đại Ngân 5</p><p>Nội thất Xuân hòa được thành lập từ năm 1980. Sau hơn 30 năm không ngừng phát triển, đến nay Xuân Hòa tự hào là một trong những doanh nghiệp hàng đầu về tư vấn, thiết kế, sản xuất trang thiết bị nội thất.</p><p class="center-red">"Mãi gắn bó, Mãi bền lâu"</p><figure><img src="img/blank-picture.jpg"><figcaption>Nhận diện thương hiệu mới nội thất xuân hòa</figcaption></figure><b>Trụ sở chính/Nhà máy</b><p>Địa chỉ: Xuân Hòa – Phúc Yên – Vĩnh Phúc</p><p>Phân phối tại Hà Nội</p><b>NỘI THẤT XUÂN HÒA</b><p>Địa chỉ: Tầng 1 Tòa nhà CT3B số 10 Đại Lộ Thăng Long, Mễ Trì, Nam Từ Liêm, Hà Nội</p><p>Điện thoại: 04 33676688 - Hotline: 0982299076</p><p class="center-black">Xin mời các bạn xem thêm thông tin về nhà máy Xuân hòa Qua Video sau</p><iframe width="100%" height="300" src="https://www.youtube.com/embed/I61l7eltucM" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>';	
		$('.about .content ').html(gioi_thieu1);
		$('.about .content ').html(gioi_thieu2);

		$('.about .menu #gioi-thieu-2').click(
			function(){
						$('.about .content ').html(gioi_thieu2);
			});
		$('.about .menu #gioi-thieu-3').click(
			function(){
				$('.about .content ').html('<p class="title">Về Đại Ngân 3</p><p>Nội thất Xuân hòa được thành lập từ năm 1980. Sau hơn 30 năm không ngừng phát triển, đến nay Xuân Hòa tự hào là một trong những doanh nghiệp hàng đầu về tư vấn, thiết kế, sản xuất trang thiết bị nội thất.</p><p class="center-red">"Mãi gắn bó, Mãi bền lâu"</p><figure><img src="img/blank-picture.jpg"><figcaption>Nhận diện thương hiệu mới nội thất xuân hòa</figcaption></figure><b>Trụ sở chính/Nhà máy</b><p>Địa chỉ: Xuân Hòa – Phúc Yên – Vĩnh Phúc</p><p>Phân phối tại Hà Nội</p><b>NỘI THẤT XUÂN HÒA</b><p>Địa chỉ: Tầng 1 Tòa nhà CT3B số 10 Đại Lộ Thăng Long, Mễ Trì, Nam Từ Liêm, Hà Nội</p><p>Điện thoại: 04 33676688 - Hotline: 0982299076</p><p class="center-black">Xin mời các bạn xem thêm thông tin về nhà máy Xuân hòa Qua Video sau</p><iframe width="100%" height="300" src="https://www.youtube.com/embed/I61l7eltucM" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>');
			});
		$('.about .menu #gioi-thieu-4').click(
			function(){
				$('.about .content ').html('<p class="title">Về Đại Ngân 4</p><p>Nội thất Xuân hòa được thành lập từ năm 1980. Sau hơn 30 năm không ngừng phát triển, đến nay Xuân Hòa tự hào là một trong những doanh nghiệp hàng đầu về tư vấn, thiết kế, sản xuất trang thiết bị nội thất.</p><p class="center-red">"Mãi gắn bó, Mãi bền lâu"</p><figure><img src="img/blank-picture.jpg"><figcaption>Nhận diện thương hiệu mới nội thất xuân hòa</figcaption></figure><b>Trụ sở chính/Nhà máy</b><p>Địa chỉ: Xuân Hòa – Phúc Yên – Vĩnh Phúc</p><p>Phân phối tại Hà Nội</p><b>NỘI THẤT XUÂN HÒA</b><p>Địa chỉ: Tầng 1 Tòa nhà CT3B số 10 Đại Lộ Thăng Long, Mễ Trì, Nam Từ Liêm, Hà Nội</p><p>Điện thoại: 04 33676688 - Hotline: 0982299076</p><p class="center-black">Xin mời các bạn xem thêm thông tin về nhà máy Xuân hòa Qua Video sau</p><iframe width="100%" height="300" src="https://www.youtube.com/embed/I61l7eltucM" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>');
			});